services:
  maleon-avatar:
    build: .
    container_name: maleon_service
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      # Pasa tu sesi√≥n de Google de Windows al contenedor
      - ${APPDATA}/gcloud:/root/.config/gcloud:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
    env_file:
      - .env
    restart: always